  <footer class="global-footer wrapper">
    <ul>
      <li><a href="#FIXME">drm-free ebook faq</a></li>
      <li><a href="#FIXME">advanced search</a></li>
      <li><a href="#FIXME">terms of use</a></li>
      <li><a href="#FIXME">privacy notice</a></li>
      <li><a href="#FIXME">about tor.com</a></li>
      <li><a href="#FIXME">tor/forge books</a></li>
      <li><a href="#FIXME">contact us</a></li>
    </ul>
  </footer>

  <div id="scripts">
    <script data-main="/scripts/main" src="/scripts/libs/require/require.js?<?=RELEASE_VERSION?>"></script>
    <link type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
  </div>

  <? //$this->load->view('includes/webtrends.inc') ?>
</body>
</html>