<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <title>lorihutchek.com</title>

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta name="description" content="<!-- put a description here -->" />
  <meta name="keywords" content="<!-- keywords here -->" />

  <meta name="google-site-verification" content="<!-- put code here -->" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

  <!-- static favicon used on older browsers -->
  <link rel="shortcut icon" href="<!-- add image path here -->" />
  <link rel="shortcut icon" href="<!-- add image path here -->" type="image/x-icon" />
  <link rel="icon" href="<!-- add image path here -->" type="image/x-icon" />

  <!-- OG tags -->
  <meta property="og:image" content="<!-- image path goes here -->"/>
  <meta property="og:site_name" content="lorihutchek.com"/>

  <!-- put your css here, make sure paths are /css/filename -->
  <link type="text/css" href="/css/global.css?<?=RELEASE_VERSION?>" rel="stylesheet">


</head>
<body class="<?=$class_id?>">